export const ACTION_TYPES = {

    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',

    INIT_INGREDIENTS: 'INIT_INGREDIENTS',
    INIT_INGREDIENTS_FAILED: 'INIT_INGREDIENTS_FAILED',

    PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILED: 'PURCHASE_BURGER_FAILED',
    PURCHASE_INIT: 'PURCHASE_INIT',

    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILED: 'FETCH_ORDERS_FAILED',

    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILED: 'AUTH_FAILED',
    LOGOUT: 'LOGOUT',

    SET_AUTH_REDIRECT_PATH: 'SET_AUTH_REDIRECT_PATH',

    // Sagas Action types
    AUTH_INITIATE_LOGOUT: 'AUTH_INITIATE_LOGOUT',
    CHECK_AUTH_TIMEOUT: 'CHECK_AUTH_TIMEOUT',
    AUTH_USER: 'AUTH_USER',
    AUTH_CHECK_STATE: 'AUTH_CHECK_STATE',
    INIT_INGREDIENTS_SAGA: 'INIT_INGREDIENTS_SAGA',
    PURCHASE_BURGER: 'PURCHASE_BURGER',
    FETCH_ORDERS: 'FETCH_ORDERS'
};